name: 1.0.1$(rev:.r)

trigger:
  - main

pool: Default

steps:

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/serverless.zip'
    replaceExistingArchive: true
  displayName: 'Zip Artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'application'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'


